MIN_COMMIT_COUNT: 100
MIN_COMMIT_MESSAGE_LENGTH: 10
MAX_COMMIT_MESSAGE_LENGTH: 4000
MAX_DIFF_LENGTH: 10000
CLONE_TIMEOUT: 30
MAX_WORKERS: 300
DIRTY_DATA_PATH: 'output/'
GITS_PATH: 'git/'
URLS_PATH: 'url/'
CLEANED_AND_MERGED_FILE_PATH: 'cleaned_output.csv'